doc.type.html
script
filename=covid strings18gamecode.js
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
jbutton random button
new jbutton (set random color)
private final j button option button=
new j button (change color)
public fun with graphics()
jpanel color panel=new j panel();
this add (panel,center)
jpanel button panel=
new j panel(flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener()
override 
public actionperformed(actionevent e)
random r =newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13)(rnextint(13)(rnextint(13)(rnextint(13)(rnextint(13)(rnextint(13)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel, borderlayout.south)
public static main(string [] args)
jframe f = new covid strings18()
f.set title(covid strings18)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult ==x*y)
[non-concatenated]
score+=ten
else:
score-=ten
If (mult == X*Y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
Entries Object Entries(Obj);
Value Object= [Team Color]
Covidstrings Team List18= [Blue,Indigo,Purple,Black,Orange,Red,Turquoise,Burgundy]
Covid Strings Phrase List18=[Non-Concatenated Strings
Even Dave Rubin Thinks Trump Believes His Supporters Are Morons
Perhaps Because Trump Thinks That He Can Joke About People Dying From Covid And Get Away With It
New Data Suggests That Even Though Vaccinations As A Whole Have Caught Up To Pre-Covid Levels Covid Shots Are One Exception
Contrary To Aaron Rodgerss Immunization Reinfections Are Serious No Matter How Many Times They Happen
As A Matter Of Fact Long-Term Respiratory Viruses Might Be The New Normal
This Is Especially True If Reports About China Experimenting With A New Coronavirus Are True
The One Thing Thats Probably False Is The Idea That Covid Is Retaliation For Trumps Tariffs
A Similar Falsehood Is Absolute Immunity For Covid
Concatenated Strings
Trump+Is+Probably+Wrong+On+The+Idea+That+Covid+Started+When+A+Scientist+Said+Hello+To+His+Girlfriend
It+Might+Be+More+Likely+That+Covid+Itself+Was+Created+In+A+Lab
Covid+Though+Has+Not+Killed+17+Million+People
Damaged+Mitochondria+Certainly+Do+Play+A+Role+In+Long+Covid
They+Just+Arent+The+Powerhouses+Currently+Like+Ba286+And+JN1
It+Is+Questionable+Whether+The+Current+Wave+Is+The+Second+Biggest
It+Was+A+Masked+Christmas+Is+Not+Questionable+In+A+2020+Timeframe
Vaccines+Now+Are+Clearly+The+Best+Defense+Against+Covid]
Covid Strings18 Math Problems List =[If95 Percent Strongly Believe That Covid Does Not Have Absolute Immunity How Many Mildly Believe?, If The Margin Of Error Is.25 Percent What Is The Range? ,If A Poll Found That95 Percent Believe That Covid Will Eventually Kill17 Million People How Many Do Not?, If87 Percent Believe That The Belief Of17 Million People Dying Is Exaggerated How Many Dont?,If The Margin Of Error Is9.8Percent What Is The Range?, If+Masked+Christmas+Was+Voted+2021s+Most+Listened+Christmas+Song+With+54+Percent+Support+If+The+Second+Place+One+Had+39+Percent+What+Is+The+Difference?,If+The+Third+Song+Was+Fauci+The+Snowman+With+7+Percent+What+Is+The+Difference+From+2nd+To+3rd?,if+the+second+song+was+revealed+to+be+season+of+the+sticks+is+this+survey+consistent+with
The+Amount+Of+Times+Theyre+On+The+Radio?,If+78+Percent+Viewed+The+Idea+Of+A+Scientists+Girlfriend+Creating+Covid+As+A+Funny+Joke+What+Percent+Dont?,If+The+Margin+Of+Error+Is+6.18+Percent+What+Is+The+Range?,If+59+Percent+Viewed+This+Comment+As+Pretty+Funny+How+Many+Say+It+Could+Be+Better?]
covid strings multiple choice list18=[1:a the virus plotting against democracy b absolute immunity c the idea it will leak trumps tax returns d the idea that2million in donations heals all wounds,2:a friendly fire b please accommodate republican views on the southern border c masked d trump should not be president if hes a felon,3: a vaccines b ron desantis voters staying home c trump losing his civil fraud case d capturing the kremlin,4:a desantis b romney c trump d dr.fauci,5:a meddling14 year olds b people dying from covid c scooby doo d giving putin back sanctioned assets in switzerland,6:a post covid b pre-covid c uranus like d safeguarding creativity in the age of ai,7:a covid b a tax hike on americas super rich c micheal watley being rnc chair d boris nadezdhin,
8:a reinfections b putin being off the rails c mary trumps belief on her uncle wanting to hold on to his reputation d being sanctioned by russia,9:a the dojs60 day rule b covid c joe bidens plan to win nikki haley voters d trump smearing chinese communist party officials,10:a short term respiratory viruses b long term respiratory viruses c polls showing russians do not support putins war d putin killing political prisoner,11:a books about an omicron variant b cracking papyrus scrolls  c17 million people  d  isis-k,12: a china b hamas c boko haram d kazakhstan,13:a mitochondria b lafayette square protesters c profits for russian prisons d concert halls,14:a citizen k b trump wanting to avoid being implicated in the jeffery epstein scandal c trumps tariffs d putins weakness being exposed,
15:a the russian economy b old soviet files  c ba286  d bidens2024 election,16:a2020 b2034 c2046 d2008,17:a post b pre c during d discovering planet nine,18:a covid b putins obsession with power c banning trump from the2024 ballot d a crackdown on russian artists,19:a biden b obama c yolanda davis d trump in the gop primary,20: a covid b full presidential immunity c shipilkins razor d protests against viktor orban,21:a create a new delta variant b say chinas population collapsing is good c joke d not care about having polling problems,
22:a yes b no ]
covid strings sentencelist18=[while russia helped to elect trump covid did not elect biden,its easy to see why covid could kill 17 million people, trump joking about president for life gives him the perception that he can joke about covid after being infected,a+masked+christmas+certainly+is+a+2020+capsule,one+hopes+that+vaccinations+post+covid+dont+decrease,a+scientist+saying+hello+to+his+girlfriend+causing+covid+is+funny] 
userin.select team
import meta.
class myclass
constructor (non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax 
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct:
return false
else: 
return true
return filename
