doc.type.html
script
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
filename=covid strings18gamecode.js
java.awt graphics 
<div id=header></div>
jbutton random button
new button (set random color)
private final j button option button=
new button (change color)
public fun with graphics()
color panel=new j panel();
add (panel,center)
jpanel button panel=
new j panel(flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r =newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13)(rnextint(13)(rnextint(13)(rnextint(13)(rnextint(13)(rnextint(13)))
num teams
total players=players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel, borderlayout.south)
public static main(string [] args)
jframe f = new covid strings18()
f.set title(covid strings18)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult ==x*y)
[non-concatenated]
score+=ten
else:
score-=ten
If (mult == X*Y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object=[team color]
covidstrings team list18= [blue curve crushers,indigo isos,purple brave hearts,black night riders,orange rna messengers,red protein spikers,turquoise waves,burgundy rebuilders]
covid strings phraselist18=[non-concatenated strings
"even dave rubin thinks trump believes his supporters are morons"
"perhaps because trump thinks that he can joke about people dying from covid and get away with it"
"new data suggests that even though vaccinations as a whole have caught up to pre-covid levels covid shots are one exception"
"contrary to aaron rodgers's immunization reinfections are serious no matter how many times they happen"
"as a matter of fact long-term respiratory viruses might be the new normal"
"this is especially true if reports about china experimenting with a new coronavirus are true"
"the one thing thats probably false is the idea that covid is retaliation for trumps tariffs"
"a similar falsehood is absolute immunity for covid"
concatenated strings
"trump"+"is"+"probably"+"wrong"+"on"+"the"+"idea"+"that"+"covid"+"started"+"when"+"a"+"scientist"+"said"+"hello"+"to"+"his"+"girlfriend"
"it"+"might"+"be"+"more"+"likely"+"that"+"covid"+"itself"+"was"+"created"+"in"+"a"+"lab"
"covid"+"though"+"has"+"not"+"killed"+"17"+"million"+"people"
"damaged"+"mitochondria"+"certainly"+"do"+"play"+"a"+"role"+"in"+"long"+"covid"
"they"+"just"+"arent"+"the"+"powerhouses"+"currently"+"like"+"ba286"+"and"+"jn1"
"it"+"is"+"questionable"+"whether"+"the"+"current"+"wave"+"is"+"the"+"second"+"biggest"
"it"+"was"+"a"+"masked"+"christmas"+"is"+"not"+"questionable"+"in"+"a"+"2020"+"timeframe"
"vaccines"+"now"+"are"+"clearly"+"the"+"best"+"defense"+"against"+"covid"]
covidstrings18 mathproblemslist =[ non-concatenated "if95 percent strongly believe that covid does not have absolute immunity how many mildly believe"?,"if the margin of error Is.25 percent what is the range?","if a poll found that95 percent believe that covid will eventually kill 17million people how many do not"?,"if87 percent believe that the belief of17 million people dying is exaggerated how many dont"?,"if the margin of error Is9.8 percent what is the range?", 
concatenated "if"+"masked"+"christmas"+"was"+"voted"+"2021s"+"most"+"listened"+"christmas"+"song"+"with"+"54"+"percent"+"support"+"if"+"the"+"second"+"place"+"one"+"had"+"39"+"percent"+"what"+"is"+"the"+"difference"?,"if"+"the"+"third"+"song"+"was"+"fauci"+"the"+"snowman"+"with"+"7"+"percent"+"what"+"is"+"the"+"difference"+"from"+"2nd"+"To"+"3rd"?,"if"+"the"+"second"+"song"+"was"+"revealed"+"to"+"be"+"season"+"of"+"the"+"sticks"+"is"+"this"+"survey"+"consistent"+"with"
"the"+"amount"+"of"+"times"+"theyre"+"on"+"the"+"radio"?,"if"+"78"+"percent"+"viewed"+"the"+"idea"+"of"+"a"+"scientists"+"girlfriend"+"creating"+"covid"+"as"+"a"+"funny"+"joke"+"what"+"percent"+"dont"?,"if"+"the"+"margin"+"of"+"error"+"is"+"6.18"+"percent"+"what"+"is"+"the"+"range"?,"if+"59"+"percent"+"viewed"+"this"+"comment"+"as"+"pretty"+"funny"+"how"+"many"+"say"+"it"+"could"+"be"+"better"?]
covid strings multiple choice list18=[1:a the virus plotting against democracy b absolute immunity c the idea it will leak trumps tax returns d the idea that2million in donations heals all wounds,2:a friendly fire b please accommodate republican views on the southern border c masked d trump should not be president if hes a felon,3: a vaccines b ron desantis voters staying home c trump losing his civil fraud case d capturing the kremlin,4:a desantis b romney c trump d dr.fauci,5:a meddling14 year olds b people dying from covid c scooby doo d giving putin back sanctioned assets in switzerland,6:a post covid b pre-covid c uranus like d safeguarding creativity in the age of ai,7:a covid b a tax hike on americas super rich c micheal watley being rnc chair d boris nadezdhin,
8:a reinfections b putin being off the rails c mary trumps belief on her uncle wanting to hold on to his reputation d being sanctioned by russia,9:a the dojs60 day rule b covid c joe bidens plan to win nikki haley voters d trump smearing chinese communist party officials,10:a short term respiratory viruses b long term respiratory viruses c polls showing russians do not support putins war d putin killing political prisoner,11:a books about an omicron variant b cracking papyrus scrolls  c17 million people  d  isis-k,12: a china b hamas c boko haram d kazakhstan,13:a mitochondria b lafayette square protesters c profits for russian prisons d concert halls,14:a citizen k b trump wanting to avoid being implicated in the jeffery epstein scandal c trumps tariffs d putins weakness being exposed,
15:a the russian economy b old soviet files  c ba286  d bidens2024 election,16:a2020 b2034 c2046 d2008,17:a post b pre c during d discovering planet nine,18:a covid b putins obsession with power c banning trump from the2024 ballot d a crackdown on russian artists,19:a biden b obama c yolanda davis d trump in the gop primary,20: a covid b full presidential immunity c shipilkins razor d protests against viktor orban,21:a create a new delta variant b say chinas population collapsing is good c joke d not care about having polling problems,
22:a yes b no ]
covid strings sentencelist18=["while russia helped to elect trump covid did not elect biden","its easy to see why covid could kill 17 million people","trump joking about president for life gives him the perception that he can joke about covid after being infected","a"+"masked"+"christmas"+"certainly"+"is"+"a"+"2020"+"capsule","one"+"hopes"+"that"+"vaccinations"+"post"+"covid"+"dont"+"decrease","a"+"scientist"+"saying"+"hello"+"to"+"his"+"girlfriend"+"causing"+"covid"+"is"+"funny"] 
userin.select team
import meta.
class myclass
constructor (non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax 
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct:
return false
else: 
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals((correctanswer))
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet) 
if users team wins covid strings18 
console log users team wins covid strings18 
else
return game over
return filename
