doc.type.html
script
filename=covid strings 18 key words.js
covid strings 18 key word list=[similar falsehood,not questionable in 2020,best covid defense,supporters are morons,trump thinks he can joke,54-39,covid shots one exception,scientist said hello to his girlfriend,aaron rodgers immunization,created in a lab,new normal,covid has not killed,experimenting with new coronaviruses,long covid,covid retaliation false,jn1,one hopes vaccinations dont,covid did not elect,its easy to see]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
covid strings 18 reference list=[a:how long does immunity last after covid-19? what we know (healthline.com),b:judges sound wary of trumps sweeping immunity claim |time,c:jimmy fallon,ariana grande,megan thee stallion drop collab (vulture.com),d:wake up! were still in a pandemic.and vaccines are our best defense against long covid.(msn.com),e:trump thinks supporters are bunch of morons:conservative commentator (msn.com),f:donald trump slammed for joking about people dying from covid-19 (msn.com),g:jimmy fallon - it was a (masked christmas) ft.ariana grande,megan thee stallion (youtube.com), 
h:america is having a senior moment on vaccines (msn.com),i:donald trump speculates wildly about how covid-19 started:a scientist went out,said hello to his girlfriend...(msn.com),j:this is what aaron rodgers has said about his covid-19 vaccine status |cnn, k:is this the smoking gun for the covid lab leak? blueprint for creating a sars-cov virus with an altered spike protein in wuhan was published in 2018,bombshell new records show |daily mail online,l:long-term respiratory illness is here to stay (msn.com),m:is it dangerous to keep getting covid-19? (msn.com),
n:china experimenting with new deadly coronavirus-like virus that is 100% fatal to mice (msn.com),o:long covid:damaged mitochondria in muscles might be linked to some of the symptoms (msn.com),p:trump muses:maybe covid-19 was punishment for his tariffs on china? (msn.com),q:new,highly mutated covid variants pirola ba.2.86 and jn.1 may cause more severe disease,new studies suggest (msn.com),r:tucker carlson video spreads falsehoods on covid-19 vaccines,who accord (msn.com),s:amazon.com:the plot to destroy democracy:how putin and his spies are undermining america and dismantling the west: 9780316484817: nance, malcolm, reiner, rob: libros,
t:is this covid surge really the second biggest? heres what data shows.(msn.com)]
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
b=pc.create script(B);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
D=Pc.CreateScript(D);
D.Attributes.Add(Foobar, {Type:Entity});
D.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
E=Pc.CreateScript(E);
E.Attributes.Add(Foobar, {Type:Entity});
E.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
F=Pc.CreateScript(F);
F.Attributes.Add(Foobar, {Type:Entity});
F.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
G=Pc.CreateScript(G);
G.Attributes.Add(Foobar, {Type:Entity});
G.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
H=Pc.CreateScript(H);
H.Attributes.Add(Foobar, {Type:Entity});
H.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
I=Pc.CreateScript(I);
I.Attributes.Add(Foobar, {Type:Entity});
I.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
J=Pc.CreateScript(J);
J.Attributes.Add(Foobar, {Type:Entity});
J.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
K=Pc.CreateScript(K);
K.Attributes.Add(Foobar, {Type:Entity});
K.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
L=Pc.CreateScript(L);
L.Attributes.Add(Foobar, {Type:Entity});
L.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
M=Pc.CreateScript(M);
M.Attributes.Add(Foobar, {Type:Entity});
M.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
N=Pc.CreateScript(N);
N.Attributes.Add(Foobar, {Type:Entity});
N.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
O=Pc.CreateScript(O);
O.Attributes.Add(Foobar, {Type:Entity});
O.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset=This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar =This Entity
Entity Reparnet (This.Entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
q=pc.create script(q);
q.attributes.add(foobar, {type:entity});
q.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
r=pc.create script(r);
r.attributes.add(foobar,{type:entity});
r.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
s=pc.create script(s);
s.attributes.add(foobar,{type:entity});
s.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar =this entity
entity reparnet (this.entity)
t=pc.create script(t);
t.attributes.add(foobar,{type:entity});
t.prototype.initialize=function() 
console.log(this.foobar.name);
return filename
